SELECT * FROM customer;
SELECT LOWER(first_name) , LOWER(last_name), LOWER(email) FROM customer WHERE (LENGTH(first_name) > 10 OR LENGTH(last_name) > 10);
SELECT RIGHT(email,5) FROM customer;
SELECT email FROM customer WHERE email LIKE '%.org';
SELECT LEFT(RIGHT(email,4),1) FROM customer;
SELECT LEFT(email,1) ||'***' || RIGHT(email,19) AS anonymized_email FROM customer;
SELECT LEFT(last_name, POSITION('@' IN email)-1) ||',' || LEFT(email,POSITION(last_name IN email)-2) FROM customer;
SELECT '***' || RIGHT(first_name,1) || SUBSTRING(email FROM POSITION ('.' in email) for 1) || LEFT(last_name,1) || '***' || SUBSTRING (email FROM POSITION ('@' in email)) FROM customer;
SELECT * FROM payment;
SELECT EXTRACT(month from payment_date),SUM(amount) FROM payment GROUP BY EXTRACT(month from payment_date) ORDER BY SUM(amount) DESC; 
SELECT EXTRACT( dow from payment_date),SUM(amount) FROM payment GROUP BY EXTRACT( DOW from payment_date) ORDER BY SUM(amount) DESC;
SELECT EXTRACT(week from payment_date), SUM(amount) FROM payment GROUP BY EXTRACT(week from payment_date) ORDER BY SUM(amount) DESC ;
SELECT SUM(amount) , TO_CHAR (payment_date,'Dy, HH:MI') FROM payment GROUP BY TO_CHAR (payment_date,'Dy, HH:MI');
SELECT CURRENT_TIMESTAMP-rental_date FROM rental;
SELECT * FROM rental;
SELECT (return_date-rental_date)  FROM rental WHERE customer_id=35;
SELECT customer_id,AVG(return_date-rental_date) AS avgduration FROM rental GROUP BY customer_id ORDER BY avgduration DESC;
SELECT * FROM film;
SELECT film_id,ROUND(replacement_cost/rental_rate,2) FROM film WHERE (replacement_cost/rental_rate) < 4;